pipeline {
    agent {
        docker {
            image 'osuosl/ubuntu-s390x:22.04'
            label 's390x-docker2'
        }
    }
    
    options {
        // Shallow clone for the main repository
        skipDefaultCheckout()
    }
    
    stages {
        stage('Checkout Envoy') {
            steps {
                script {
                    dir('envoy') {
						// Shallow clone of repository
						checkout([
							$class: 'GitSCM',
							branches: [[name: '*/master']],
							extensions: [
								[$class: 'CloneOption', depth: 1, noTags: false, shallow: true]
							],
							userRemoteConfigs: [[url: 'https://github.com/envoyproxy/envoy.git']]
						])
                    }    
                }
            }
        }
        
        stage('Checkout Build files') {
            steps {
                script {
                    // Checkout OSUOSL-Jenkins/Envoy folder from scripts repository
                    dir('scripts-repo') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: '*/master']],
                            extensions: [
                                [$class: 'SparseCheckoutPaths', 
                                 sparseCheckoutPaths: [[path: 'OSUOSL-Jenkins/Envoy/*']]]
                            ],
                            userRemoteConfigs: [[url: 'https://github.com/linux-on-ibm-z/scripts.git']]
                        ])
                    }
                }
            }
        }
        
        stage('Run Script') {
            steps {
                script {
                    // Run your script here
                    // Example: sh 'bash scripts-repo/OSUOSL-Jenkins/Tensorflow/build_envoy.sh'
					sh 'pwd'
					sh 'ls -l'
                    sh 'ls -la scripts-repo/OSUOSL-Jenkins/'
                    sh 'ls -l scripts-repo/OSUOSL-Jenkins/Envoy'
                    sh 'cp scripts-repo/OSUOSL-Jenkins/Envoy/build_envoy.sh .'
					sh 'cp -r scripts-repo/OSUOSL-Jenkins/Envoy/patch patch/ .'
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
